"""Initial migration

Revision ID: ff4ac2a9ecb3
Revises:
Create Date: 2026-03-24 00:20:07.433568

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "ff4ac2a9ecb3"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
